services:
  db:
    image: mariadb
    container_name: collectors-db
    restart: no
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: secure-password
      MARIADB_USER: collection
      MARIADB_PASSWORD: collection
      MARIADB_DATABASE: collection
    volumes:
      - database:/var/lib/mysql
  php:
    build:
      context: php
      dockerfile: dockerfiles/DevDockerfile
    container_name: collectors-php
    volumes:
      - ./php/src:/var/www
  site:
    build:
      context: site
      dockerfile: dockerfiles/DevDockerfile
    command: "npm start"
    container_name: collectors-site
    environment:
      - NODE_ENV=local
    ports:
      - "4200:4200"
    user: "node"
    volumes:
      - ./site/src:/home/node/app
    working_dir: /home/node/app
  server:
    build:
      context: server
      dockerfile: dockerfiles/DevDockerfile
    container_name: collectors-server
    ports:
      - "8080:80"
    depends_on:
      - php

volumes:
  database:
